name: Nix
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-stable
    - uses: cachix/cachix-action@v8
      with:
        name: note-maps
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
    - run: nix-shell --run "make download"
    - run: nix-shell --run "make lint"
    - run: nix-shell --run "make test"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-stable
    - uses: cachix/cachix-action@v8
      with:
        name: note-maps
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
    - run: nix-shell --run "make download"
    - run: nix-shell --run "make build"
